INSERT INTO Observacao_Medica VALUES
    (default,'O paciente apresentou os sintomas de febre entre os dias 02-04-2024 a 06-04-2024', 1),
	(DEFAULT, 'Paciente se queixou de dores abdominais', 2),
    (DEFAULT, 'O paciente está respondendo bem ao tratamento', 3),
    (DEFAULT, 'Observação de rotina, paciente está estável', 4),
    (DEFAULT, 'Necessário agendar consulta de acompanhamento', 5),
	(DEFAULT, 'Paciente relatou dificuldade para respirar', 6),
    (DEFAULT, 'O paciente apresentou febre alta durante a noite', 7),
    (DEFAULT, 'Observação após cirurgia realizada com sucesso', 8),
    (DEFAULT, 'Paciente queixou-se de tonturas frequentes', 9),
    (DEFAULT, 'O paciente precisa de repouso e medicação', 10),
    (DEFAULT, 'Observação de rotina, sem alterações significativas', 11),
    (DEFAULT, 'Paciente apresentou melhora dos sintomas', 12),
    (DEFAULT, 'O paciente precisa retornar para novos exames', 13),
    (DEFAULT, 'Observação sobre a dieta do paciente', 14),
    (DEFAULT, 'Paciente está sendo monitorado de perto', 15),
    (DEFAULT, 'O paciente está recebendo visitas regulares da família', 16),
    (DEFAULT, 'Observação sobre o estado emocional do paciente', 17),
    (DEFAULT, 'Paciente precisa de acompanhamento psicológico', 18),
    (DEFAULT, 'O paciente está em isolamento por precaução', 19),
    (DEFAULT, 'Observação sobre a higiene do paciente', 20),
    (DEFAULT, 'Paciente precisa de auxílio para mobilidade', 21),
    (DEFAULT, 'Observação sobre a medicação em uso pelo paciente', 22),
    (DEFAULT, 'Paciente está se queixando de dores nas costas', 23),
    (DEFAULT, 'O paciente precisa de acompanhamento nutricional', 24),
    (DEFAULT, 'Observação sobre a pressão arterial do paciente', 25);
	