INSERT INTO Especialidade (Nome_Especialidade, Descricao_Esp) VALUES 
('Dermatologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças da pele'),
('Ginecologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças do sistema reprodutor feminino'),
('Ortopedia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças e deformidades dos ossos, músculos, ligamentos e articulações'),
('Pediatria', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças em crianças'),
('Neurologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças do sistema nervoso'),
('Oftalmologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças dos olhos'),
('Otorrinolaringologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças do ouvido, nariz e garganta'),
('Psiquiatria', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças mentais'),
('Urologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças do sistema urinário'),
('Endocrinologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças hormonais'),
('Reumatologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento de doenças das articulações, músculos e ossos'),
('Radiologia', 'Especialidade médica que se ocupa do diagnóstico por imagem'),
('Anestesiologia', 'Especialidade médica que se ocupa da anestesia e dor do paciente cirúrgico e em outros quadros clínicos'),
('Cirurgia Geral', 'Especialidade médica que se ocupa do estudo dos mecanismos fisiopatológicos, diagnóstico e tratamento de enfermidades passíveis de abordagem por procedimentos cirúrgicos'),
('Clínica Médica', 'Especialidade médica que se ocupa da prevenção, diagnóstico e tratamento de doenças em adultos, sem necessidade de cirurgia'),
('Gastroenterologia', 'Especialidade médica que se ocupa do estudo, diagnóstico e tratamento clínico das doenças do aparelho digestivo'),
('Infectologia', 'Especialidade médica que se ocupa do estudo das doenças causadas por microorganismos, sejam eles bactérias, vírus, fungos, protozoários, etc.'),
('Hematologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento das doenças do sangue e dos órgãos hematopoiéticos'),
('Nefrologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento clínico das doenças do sistema urinário, em especial das doenças do rim'),
('Pneumologia', 'Especialidade médica que se ocupa do diagnóstico e tratamento das doenças do pulmão e do aparelho respiratório');
