INSERT INTO Diagnostico VALUES
    (DEFAULT, 'Gripe', 1),
    (DEFAULT, 'Fratura', 2),
    (DEFAULT, 'Infecção', 3),
    (DEFAULT, 'Hipertensão', 4),
    (DEFAULT, 'Diabetes', 5),
    (DEFAULT, 'Enxaqueca', 6),
    (DEFAULT, 'Anemia', 7),
    (DEFAULT, 'Bronquite', 8),
    (DEFAULT, 'Câncer', 9),
    (DEFAULT, 'Dengue', 10),
    (DEFAULT, 'Obesidade', 11),
    (DEFAULT, 'Asma', 12),
    (DEFAULT, 'AVC', 13),
    (DEFAULT, 'Hepatite', 14),
    (DEFAULT, 'Pneumonia', 15),
    (DEFAULT, 'Artrite', 16),
    (DEFAULT, 'Insônia', 17),
    (DEFAULT, 'Epilepsia', 18),
    (DEFAULT, 'HIV', 19),
    (DEFAULT, 'Doença renal', 20);
