INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cardíaca');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Catarata');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Hérnia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Plástica');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Vesícula');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Apêndice');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Câncer');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Fratura');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Obesidade');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Oftalmologia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Ortopedia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Ouvido');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Rim');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Tireoide');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Coluna');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Reconstrução Facial');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Órgão');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante Capilar');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Medula');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Pele');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Rim');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Fígado');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Pulmão');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Transplante de Coração');
