INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia Cardíaca');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Catarata');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Hérnia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia Plástica');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Vesícula');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Apêndice');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Câncer');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Fratura');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Obesidade');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Oftalmologia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Ortopedia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Ouvido');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Pneumonia');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Rim');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Tireoide');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Coluna');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Reconstrução Facial');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Órgão');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante Capilar');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Medula');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Pele');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Rim');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Fígado');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Pulmão');
INSERT INTO Cirurgia (nome_Cirurgia) VALUES ('Cirurgia de Transplante de Coração');
